### ISSUE TITLE
Can't build on Android with RN 0.60.5 generateDebugRFile

### ISSUE THREAD

**Issue by Ilphrin** [tipsi/tipsi-stripe#534]
## Before I have submitted the issue 
[x] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[x] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[x] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[x] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem

We are trying to upgrade our application to React Native 0.60.5 (from 0.59.10), and we were already using tipsi-stripe then, but when upgrading RN there is this compilation error on Android Studio, saying build failed with this line 

```
/Users/myself/ourSuperApp/node_modules/tipsi-stripe/android/build/intermediates/local_only_symbol_list/debug/parseDebugLibraryResources/R-def.txt
```

And this error, shown in screenshot and detailed in Gist below, saying mainly that:

```
Caused by: java.nio.file.NoSuchFileException: /Users/pelletkevin/mon-marche.fr-app/node_modules/tipsi-stripe/android/build/intermediates/local_only_symbol_list/debug/parseDebugLibraryResources/R-def.txt
```

(Which is right, the folder `local_only_symbol_list` does not exist)

## Environment
* `tipsi-stripe` version: `7.5.1`
* Last `tipsi-stripe` version where the issue was not reproduced (if applicable): `7.5.1`, same
* iOS or Android: Android
* OS version: macOS 10.14.6
* React-Native version: 16.8.6
* (Android only) `com.google.firebase:firebase-core` version: 16.0.6
* (Android only) `com.google.android.gms:play-services-base` version: 16.1.0

## Links to logs and sources
The [GIST](https://gist.github.com/Ilphrin/ae3515da8c694aa033b4d24114786a8f)

* [ios/Podfile](https://gist.github.com/link_to_podfile)
* [android/build.gradle](https://gist.github.com/link_to_podfile)

For `Android`, please provide the following sections from `android/app/build.gradle`:
* android.compileSdkVersion: 28
* android.buildToolsVersion: 28.0.3
* android.defaultConfig.minSdkVersion: 16
* android.defaultConfig.targetSdkVersion: 28

## Screenshots, GIFs (Must to have)
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/7887258/64265427-29053680-cf33-11e9-8c15-6e0450341ec4.png">

**Comment by Jekiwijaya** [comment]
@Ilphrin have you resolved?

I just got this too
